name: deployment
on:
  push:
    branches:
      - main
jobs:
  test:
    environment: development
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: npm lint
        run: npm run lint        
      - name: Run tests
        run: npm run test      
  deploy:
    environment: development
    needs: test
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: npm install
        run: npm ci
      - name: Deploy
        run: npm run deploy